version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s bash docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    

  db:
    build:
      context: mysql
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - node-network

  proxy:
    build:
      context: nginx
    container_name: proxy
    networks:
      - node-network
    ports:
      - "8080:80"
    tty: true
    restart: always

networks:
  node-network:
    driver: bridge

volumes:
  db-volume: